/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskMakerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/models/constants.ts
var VIEW_TYPE_MATRIX = "task-maker-matrix";
var QUADRANT_CODES = ["ui", "in", "un", "nn"];
var CHECKBOX_REGEX = /^(\s*- \[)([ xX])(\]\s+)(.+)$/;
var DEFAULT_SETTINGS = {
  triggerTags: ["task", "todo"],
  tagNamespace: "T",
  phases: [],
  ui: {
    quadrantLabels: {
      ui: "\u7D27\u6025\u4E14\u91CD\u8981",
      in: "\u91CD\u8981\u4E0D\u7D27\u6025",
      un: "\u7D27\u6025\u4E0D\u91CD\u8981",
      nn: "\u4E0D\u7D27\u6025\u4E0D\u91CD\u8981"
    },
    quadrantColors: {
      ui: "#e74c3c",
      in: "#3498db",
      un: "#f39c12",
      nn: "#95a5a6"
    },
    showSourceFile: true,
    compactMode: false,
    notePanel: {
      enabled: true,
      headings: ["\u76EE\u6807", "Goals", "Plan", "\u8BA1\u5212", "\u6982\u8FF0", "Overview"],
      defaultExpanded: true
    }
  }
};

// src/services/EventBus.ts
var EventBus = class {
  constructor() {
    this.listeners = /* @__PURE__ */ new Map();
  }
  on(event, callback) {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, /* @__PURE__ */ new Set());
    }
    this.listeners.get(event).add(callback);
  }
  off(event, callback) {
    const set = this.listeners.get(event);
    if (set) {
      set.delete(callback);
    }
  }
  emit(event, payload) {
    const set = this.listeners.get(event);
    if (set) {
      set.forEach((cb) => {
        try {
          cb(payload);
        } catch (e) {
          console.error(`[TaskMaker] EventBus error on "${event}":`, e);
        }
      });
    }
  }
  clear() {
    this.listeners.clear();
  }
};

// src/services/TagManagerService.ts
var import_obsidian = require("obsidian");
var TagManagerService = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
  }
  /** Get the tag prefix, e.g. "T/" or "" if no namespace */
  getPrefix() {
    const ns = this.getSettings().tagNamespace.trim();
    return ns ? `${ns}/` : "";
  }
  /** Build a regex that matches quadrant tags with the current namespace */
  buildQuadrantRegex() {
    const prefix = this.escapeRegex(this.getPrefix());
    return new RegExp(`#${prefix}([a-zA-Z0-9_]+)-(ui|in|un|nn)\\b`, "g");
  }
  /**
   * Parse all quadrant tags from a line of text.
   * Returns a record of viewId -> QuadrantCode.
   */
  parseQuadrantTags(line) {
    const assignments = {};
    const regex = this.buildQuadrantRegex();
    let match;
    while ((match = regex.exec(line)) !== null) {
      const viewId = match[1];
      const quadrant = match[2];
      assignments[viewId] = quadrant;
    }
    return assignments;
  }
  /**
   * Build a new line with the quadrant tag for a specific viewId updated.
   * If newQuadrant is null, the tag for that viewId is removed.
   */
  buildUpdatedLine(rawLine, viewId, newQuadrant) {
    const prefix = this.getPrefix();
    const escapedPrefix = this.escapeRegex(prefix);
    const tagPattern = new RegExp(
      `\\s*#${escapedPrefix}${this.escapeRegex(viewId)}-(ui|in|un|nn)\\b`,
      "g"
    );
    const hasExisting = tagPattern.test(rawLine);
    if (hasExisting) {
      tagPattern.lastIndex = 0;
      if (newQuadrant === null) {
        return rawLine.replace(tagPattern, "").replace(/\s{2,}/g, " ").trim();
      } else {
        return rawLine.replace(tagPattern, ` #${prefix}${viewId}-${newQuadrant}`);
      }
    } else if (newQuadrant !== null) {
      return `${rawLine} #${prefix}${viewId}-${newQuadrant}`;
    }
    return rawLine;
  }
  /**
   * Update a task's quadrant tag in its source file atomically.
   */
  async updateQuadrantTag(task, viewId, newQuadrant) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian.TFile))
      return false;
    const expectedRaw = task.rawLine;
    const newLine = this.buildUpdatedLine(expectedRaw, viewId, newQuadrant);
    if (newLine === expectedRaw)
      return true;
    let success = false;
    await this.app.vault.process(file, (content) => {
      const lines = content.split("\n");
      if (task.lineNumber < lines.length && lines[task.lineNumber] === expectedRaw) {
        lines[task.lineNumber] = newLine;
        success = true;
        return lines.join("\n");
      }
      const idx = lines.indexOf(expectedRaw);
      if (idx !== -1) {
        lines[idx] = newLine;
        success = true;
        return lines.join("\n");
      }
      return content;
    });
    return success;
  }
  /**
   * Toggle the checkbox state in the source file.
   */
  async toggleTaskCompletion(task) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian.TFile))
      return false;
    const expectedRaw = task.rawLine;
    const newCompleted = !task.completed;
    const newLine = newCompleted ? expectedRaw.replace(/^(\s*- \[) \]/, "$1x]") : expectedRaw.replace(/^(\s*- \[)[xX]\]/, "$1 ]");
    if (newLine === expectedRaw)
      return false;
    let success = false;
    await this.app.vault.process(file, (content) => {
      const lines = content.split("\n");
      if (task.lineNumber < lines.length && lines[task.lineNumber] === expectedRaw) {
        lines[task.lineNumber] = newLine;
        success = true;
        return lines.join("\n");
      }
      const idx = lines.indexOf(expectedRaw);
      if (idx !== -1) {
        lines[idx] = newLine;
        success = true;
        return lines.join("\n");
      }
      return content;
    });
    return success;
  }
  /**
   * Strip all quadrant tags from a line to produce clean display text.
   * Also strips the trigger tags like #task, #todo.
   */
  cleanDisplayText(rawLine, triggerTags) {
    let text = rawLine;
    text = text.replace(/^\s*- \[[ xX]\]\s+/, "");
    const regex = this.buildQuadrantRegex();
    text = text.replace(regex, "");
    for (const tag of triggerTags) {
      const hashTag = "#" + tag;
      let result = "";
      let searchFrom = 0;
      while (true) {
        const idx = text.indexOf(hashTag, searchFrom);
        if (idx === -1) {
          result += text.slice(searchFrom);
          break;
        }
        const endPos = idx + hashTag.length;
        const beforeOk = idx === 0 || text[idx - 1] === " " || text[idx - 1] === "	";
        const afterOk = endPos >= text.length || text[endPos] === " " || text[endPos] === "	" || text[endPos] === "#" || text[endPos] === "\n";
        if (beforeOk && afterOk) {
          result += text.slice(searchFrom, idx);
          searchFrom = endPos;
        } else {
          result += text.slice(searchFrom, endPos);
          searchFrom = endPos;
        }
      }
      text = result;
    }
    return text.replace(/\s{2,}/g, " ").trim();
  }
  escapeRegex(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
};

// src/services/TaskScannerService.ts
var import_obsidian2 = require("obsidian");
var TaskScannerService = class {
  // filePath -> phase info
  constructor(app, tagManager, eventBus, getSettings) {
    this.app = app;
    this.tagManager = tagManager;
    this.eventBus = eventBus;
    this.getSettings = getSettings;
    this.taskCache = /* @__PURE__ */ new Map();
    // filePath -> tasks
    this.detectedPhases = /* @__PURE__ */ new Map();
  }
  /** Get all cached tasks as a flat array */
  getAllTasks() {
    const all = [];
    this.taskCache.forEach((tasks) => all.push(...tasks));
    return all;
  }
  /** Get all detected phase notes from last scan */
  getDetectedPhases() {
    return Array.from(this.detectedPhases.values());
  }
  /** Full scan of the entire vault */
  async fullScan() {
    this.taskCache.clear();
    this.detectedPhases.clear();
    const files = this.app.vault.getMarkdownFiles();
    const total = files.length;
    this.eventBus.emit("scan-progress", { scanned: 0, total });
    const batchSize = 50;
    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      await Promise.all(batch.map((f) => this.scanFile(f)));
      const scanned = Math.min(i + batchSize, total);
      this.eventBus.emit("scan-progress", { scanned, total });
      if (i + batchSize < files.length) {
        await sleep(0);
      }
    }
    this.eventBus.emit("scan-complete", { tasks: this.getAllTasks() });
  }
  /** Scan a single file and update cache. forceExtract=true skips trigger check. */
  async scanFile(file, forceExtract = false) {
    var _a, _b;
    const settings = this.getSettings();
    const content = await this.app.vault.cachedRead(file);
    const cache = this.app.metadataCache.getFileCache(file);
    const hasFrontmatterTrigger = this.checkFrontmatterTrigger(cache, settings.triggerTags);
    this.detectPhaseFromFrontmatter(file, cache);
    const isPhaseNote = this.detectedPhases.has(file.path) || settings.phases.some((p) => p.noteFilePath === file.path);
    const shouldForce = forceExtract || isPhaseNote;
    const lines = content.split("\n").map((l) => l.replace(/\r$/, ""));
    const tasks = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const match = CHECKBOX_REGEX.exec(line);
      if (!match)
        continue;
      const completed = match[2].toLowerCase() === "x";
      const taskContent = match[4];
      const hasInlineTrigger = this.hasInlineTriggerTag(taskContent, settings.triggerTags);
      if (!shouldForce && !hasFrontmatterTrigger && !hasInlineTrigger) {
        continue;
      }
      const quadrantAssignments = this.tagManager.parseQuadrantTags(line);
      const text = this.tagManager.cleanDisplayText(line, settings.triggerTags);
      const indentLevel = ((_b = (_a = line.match(/^\t*/)) == null ? void 0 : _a[0]) != null ? _b : "").length;
      tasks.push({
        id: `${file.path}:${i}`,
        text,
        rawLine: line,
        filePath: file.path,
        lineNumber: i,
        completed,
        triggerType: shouldForce ? "frontmatter" : hasFrontmatterTrigger ? "frontmatter" : "inline",
        quadrantAssignments,
        indentLevel
      });
    }
    this.taskCache.set(file.path, tasks);
    return tasks;
  }
  /** Incremental scan for a single modified file */
  async incrementalScan(file) {
    const tasks = await this.scanFile(file);
    this.eventBus.emit("tasks-changed", { filePath: file.path, tasks });
  }
  /** Check if file's frontmatter tags contain any trigger tag */
  checkFrontmatterTrigger(cache, triggerTags) {
    if (!cache)
      return false;
    const allTags = (0, import_obsidian2.getAllTags)(cache);
    if (!allTags || allTags.length === 0)
      return false;
    const fmTags = this.extractFrontmatterTags(cache);
    return triggerTags.some(
      (trigger) => fmTags.some((ft) => ft.toLowerCase() === trigger.toLowerCase())
    );
  }
  /** Extract tag strings from frontmatter, stripping # prefix, handling all formats */
  extractFrontmatterTags(cache) {
    const tags = [];
    if (!cache.frontmatter)
      return tags;
    const sources = [
      cache.frontmatter.tags,
      cache.frontmatter.tag
    ];
    for (const raw of sources) {
      if (Array.isArray(raw)) {
        for (const t of raw) {
          if (typeof t === "string") {
            tags.push(t.replace(/^#/, ""));
          }
        }
      } else if (typeof raw === "string") {
        const parts = raw.split(",");
        for (const p of parts) {
          const trimmed = p.trim().replace(/^#/, "");
          if (trimmed)
            tags.push(trimmed);
        }
      }
    }
    if (tags.length === 0 && cache.frontmatter) {
      const allTags = (0, import_obsidian2.getAllTags)(cache);
      if (allTags) {
        tags.push(...allTags.map((t) => t.replace(/^#/, "")));
      }
    }
    return tags;
  }
  /** Check if a task line's content contains any trigger tag (Unicode-safe) */
  hasInlineTriggerTag(content, triggerTags) {
    for (const tag of triggerTags) {
      const hashTag = "#" + tag;
      let searchFrom = 0;
      while (true) {
        const idx = content.indexOf(hashTag, searchFrom);
        if (idx === -1)
          break;
        const endPos = idx + hashTag.length;
        if (idx > 0) {
          const prevChar = content[idx - 1];
          if (prevChar !== " " && prevChar !== "	") {
            searchFrom = endPos;
            continue;
          }
        }
        if (endPos >= content.length)
          return true;
        const nextChar = content[endPos];
        if (nextChar === " " || nextChar === "	" || nextChar === "#" || nextChar === "\n") {
          return true;
        }
        searchFrom = endPos;
      }
    }
    return false;
  }
  clearCache() {
    this.taskCache.clear();
    this.detectedPhases.clear();
  }
  /** Detect phase definition from frontmatter properties or tags */
  detectPhaseFromFrontmatter(file, cache) {
    if (!(cache == null ? void 0 : cache.frontmatter)) {
      this.detectedPhases.delete(file.path);
      return;
    }
    const hasPhaseProperty = cache.frontmatter["phase"] === true || cache.frontmatter["phase"] === "true";
    const fmTags = this.extractFrontmatterTags(cache);
    const hasPhaseTag = fmTags.some((t) => t.toLowerCase() === "phase");
    if (!hasPhaseProperty && !hasPhaseTag) {
      this.detectedPhases.delete(file.path);
      return;
    }
    const phaseId = cache.frontmatter["phase-id"];
    const phaseLabel = cache.frontmatter["phase-label"];
    if (typeof phaseId === "string" && phaseId.trim()) {
      const phaseStart = cache.frontmatter["phase-start"];
      const phaseEnd = cache.frontmatter["phase-end"];
      const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
      const timePeriod = typeof phaseStart === "string" && dateRegex.test(phaseStart) && typeof phaseEnd === "string" && dateRegex.test(phaseEnd) ? { start: phaseStart, end: phaseEnd } : void 0;
      this.detectedPhases.set(file.path, {
        phaseId: phaseId.trim(),
        phaseLabel: typeof phaseLabel === "string" && phaseLabel.trim() ? phaseLabel.trim() : phaseId.trim(),
        filePath: file.path,
        timePeriod
      });
    } else {
      this.detectedPhases.delete(file.path);
    }
  }
};
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// src/services/ViewRegistryService.ts
var ViewRegistryService = class {
  constructor(getSettings) {
    this.getSettings = getSettings;
  }
  /** Get a view definition by its ID */
  getView(viewId) {
    const phase = this.getSettings().phases.find((p) => p.id === viewId);
    if (phase) {
      return {
        id: phase.id,
        type: "phase",
        label: phase.label,
        parentId: null,
        timePeriod: phase.timePeriod
      };
    }
    return void 0;
  }
  /** Get all phase view definitions */
  getPhaseViews() {
    return this.getSettings().phases.sort((a, b) => a.order - b.order).map((p) => ({
      id: p.id,
      type: "phase",
      label: p.label,
      parentId: null,
      timePeriod: p.timePeriod
    }));
  }
  /** Validate that a phase ID is well-formed and unique */
  isValidPhaseId(id) {
    if (!id || id.length === 0) {
      return { valid: false, reason: "ID cannot be empty" };
    }
    if (id.length > 20) {
      return { valid: false, reason: "ID must be 20 characters or less" };
    }
    if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(id)) {
      return { valid: false, reason: "ID must start with a letter and contain only letters, numbers, and underscores" };
    }
    if (this.getSettings().phases.some((p) => p.id === id)) {
      return { valid: false, reason: "Phase ID already exists" };
    }
    return { valid: true };
  }
  /** Determine the view type of a given viewId */
  getViewType(viewId) {
    if (this.getSettings().phases.some((p) => p.id === viewId)) {
      return "phase";
    }
    return void 0;
  }
};

// src/ui/MatrixView.ts
var import_obsidian5 = require("obsidian");

// src/ui/DragDropManager.ts
var DragDropManager = class {
  constructor(app, tagManager, eventBus, getCurrentViewId, getTaskById) {
    this.app = app;
    this.tagManager = tagManager;
    this.eventBus = eventBus;
    this.getCurrentViewId = getCurrentViewId;
    this.getTaskById = getTaskById;
    this.currentDragTaskId = null;
  }
  /** Make a task element draggable */
  setupDraggable(el, taskId) {
    el.draggable = true;
    el.dataset.taskId = taskId;
    el.addEventListener("dragstart", (e) => {
      var _a;
      this.currentDragTaskId = taskId;
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", taskId);
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
      }
      el.classList.add("tm-dragging");
      requestAnimationFrame(() => {
        el.style.opacity = "0.4";
      });
    });
    el.addEventListener("dragend", () => {
      this.currentDragTaskId = null;
      el.classList.remove("tm-dragging");
      el.style.opacity = "";
    });
  }
  /** Make a quadrant cell a drop target */
  setupDropZone(el, quadrant) {
    el.addEventListener("dragover", (e) => {
      e.preventDefault();
      if (e.dataTransfer) {
        e.dataTransfer.dropEffect = "move";
      }
      el.classList.add("tm-drag-over");
    });
    el.addEventListener("dragleave", (e) => {
      const related = e.relatedTarget;
      if (!related || !el.contains(related)) {
        el.classList.remove("tm-drag-over");
      }
    });
    el.addEventListener("drop", async (e) => {
      var _a;
      e.preventDefault();
      el.classList.remove("tm-drag-over");
      const taskId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!taskId)
        return;
      const task = this.getTaskById(taskId);
      if (!task)
        return;
      const viewId = this.getCurrentViewId();
      const currentQuadrant = task.quadrantAssignments[viewId];
      if (currentQuadrant === quadrant)
        return;
      const success = await this.tagManager.updateQuadrantTag(task, viewId, quadrant);
      if (success) {
        this.eventBus.emit("task-updated", { taskId, viewId, quadrant });
      }
    });
  }
  /** Make the unassigned tray a drop target that removes quadrant assignment */
  setupUnassignedDropZone(el) {
    el.addEventListener("dragover", (e) => {
      e.preventDefault();
      if (e.dataTransfer) {
        e.dataTransfer.dropEffect = "move";
      }
      el.classList.add("tm-drag-over");
    });
    el.addEventListener("dragleave", (e) => {
      const related = e.relatedTarget;
      if (!related || !el.contains(related)) {
        el.classList.remove("tm-drag-over");
      }
    });
    el.addEventListener("drop", async (e) => {
      var _a;
      e.preventDefault();
      el.classList.remove("tm-drag-over");
      const taskId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (!taskId)
        return;
      const task = this.getTaskById(taskId);
      if (!task)
        return;
      const viewId = this.getCurrentViewId();
      if (!(viewId in task.quadrantAssignments))
        return;
      const success = await this.tagManager.updateQuadrantTag(task, viewId, null);
      if (success) {
        this.eventBus.emit("task-updated", { taskId, viewId, quadrant: null });
      }
    });
  }
};

// src/ui/components/PhaseSelector.ts
var PhaseSelector = class {
  constructor(container, viewRegistry, eventBus) {
    this.container = container;
    this.viewRegistry = viewRegistry;
    this.eventBus = eventBus;
    this.currentViewId = "";
    this.el = container.createDiv({ cls: "tm-phase-selector" });
    this.refresh();
  }
  refresh() {
    this.el.empty();
    const phases = this.viewRegistry.getPhaseViews();
    if (phases.length === 0) {
      this.el.createSpan({
        cls: "tm-phase-empty",
        text: "(\u65E0\u9636\u6BB5 - \u8BF7\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0)"
      });
      return;
    }
    for (const phase of phases) {
      const btn = this.el.createEl("button", {
        cls: "tm-phase-btn",
        text: phase.label
      });
      btn.dataset.viewId = phase.id;
      if (phase.id === this.currentViewId) {
        btn.classList.add("tm-phase-btn-active");
      }
      btn.addEventListener("click", () => {
        this.eventBus.emit("view-switched", { viewId: phase.id, viewType: "phase" });
      });
    }
  }
  setCurrentPhase(viewId) {
    this.currentViewId = viewId;
    this.el.querySelectorAll(".tm-phase-btn").forEach((btn) => {
      const el = btn;
      el.classList.toggle("tm-phase-btn-active", el.dataset.viewId === viewId);
    });
  }
};

// src/ui/components/ViewNavigator.ts
var ViewNavigator = class {
  constructor(container, viewRegistry, eventBus, onAddPhase, onToggleFilter) {
    this.container = container;
    this.viewRegistry = viewRegistry;
    this.eventBus = eventBus;
    this.onAddPhase = onAddPhase;
    this.onToggleFilter = onToggleFilter;
    this.hideCompleted = false;
    this.phaseCollapsed = false;
    this.timelineActive = false;
    this.el = container.createDiv({ cls: "tm-nav-bar" });
    const topRow = this.el.createDiv({ cls: "tm-nav-top-row" });
    this.phaseToggleBtn = topRow.createEl("button", {
      cls: "tm-phase-toggle-btn",
      attr: { "aria-label": "\u6298\u53E0/\u5C55\u5F00\u9636\u6BB5\u9009\u62E9\u5668" }
    });
    this.phaseToggleBtn.innerHTML = '<span class="tm-phase-toggle-icon">\u25BC</span> \u9636\u6BB5';
    this.phaseToggleBtn.addEventListener("click", () => {
      this.phaseCollapsed = !this.phaseCollapsed;
      this.phaseControlsEl.style.display = this.phaseCollapsed ? "none" : "flex";
      this.phaseToggleBtn.classList.toggle("tm-phase-collapsed", this.phaseCollapsed);
      const icon = this.phaseToggleBtn.querySelector(".tm-phase-toggle-icon");
      if (icon)
        icon.textContent = this.phaseCollapsed ? "\u25B6" : "\u25BC";
    });
    this.filterBtn = topRow.createEl("button", {
      cls: "tm-filter-toggle-btn",
      text: "\u9690\u85CF\u5DF2\u5B8C\u6210"
    });
    this.filterBtn.addEventListener("click", () => {
      var _a;
      this.hideCompleted = !this.hideCompleted;
      this.filterBtn.classList.toggle("tm-filter-active", this.hideCompleted);
      this.filterBtn.textContent = this.hideCompleted ? "\u663E\u793A\u5168\u90E8" : "\u9690\u85CF\u5DF2\u5B8C\u6210";
      (_a = this.onToggleFilter) == null ? void 0 : _a.call(this);
    });
    this.timelineBtn = topRow.createEl("button", {
      cls: "tm-timeline-toggle-btn",
      attr: { "aria-label": "\u5207\u6362\u65F6\u95F4\u8F74\u603B\u89C8" }
    });
    this.timelineBtn.textContent = "\u65F6\u95F4\u8F74";
    this.timelineBtn.addEventListener("click", () => {
      this.timelineActive = !this.timelineActive;
      this.timelineBtn.classList.toggle("tm-timeline-active", this.timelineActive);
      if (this.timelineActive) {
        this.phaseControlsEl.style.display = "none";
      } else if (!this.phaseCollapsed) {
        this.phaseControlsEl.style.display = "flex";
      }
      this.eventBus.emit("timeline-toggled", { active: this.timelineActive });
    });
    this.scanHostEl = topRow.createDiv({ cls: "tm-scan-host" });
    this.phaseControlsEl = this.el.createDiv({ cls: "tm-phase-controls" });
    this.phaseSelector = new PhaseSelector(this.phaseControlsEl, viewRegistry, eventBus);
    if (this.onAddPhase) {
      const addBtn = this.phaseControlsEl.createEl("button", {
        cls: "tm-add-phase-btn",
        text: "+",
        attr: { "aria-label": "\u6DFB\u52A0\u9636\u6BB5\u5C5E\u6027\u5230\u5F53\u524D\u7B14\u8BB0" }
      });
      addBtn.addEventListener("click", () => this.onAddPhase());
    }
  }
  updatePhaseView(viewId) {
    this.phaseSelector.setCurrentPhase(viewId);
  }
  refreshPhases() {
    this.phaseSelector.refresh();
  }
  getScanHost() {
    return this.scanHostEl;
  }
  isHideCompleted() {
    return this.hideCompleted;
  }
  isTimelineActive() {
    return this.timelineActive;
  }
  setTimelineActive(active) {
    this.timelineActive = active;
    this.timelineBtn.classList.toggle("tm-timeline-active", active);
    if (active) {
      this.phaseControlsEl.style.display = "none";
    } else if (!this.phaseCollapsed) {
      this.phaseControlsEl.style.display = "flex";
    }
  }
};

// src/ui/components/PhaseNotePanel.ts
var import_obsidian3 = require("obsidian");

// src/ui/utils/noteContentExtractor.ts
function extractNoteContent(rawContent, targetHeadings) {
  if (!rawContent || targetHeadings.length === 0)
    return "";
  const lines = rawContent.split("\n");
  const lowerTargets = targetHeadings.map((h) => h.toLowerCase());
  const resultBlocks = [];
  let capturing = false;
  let captureLevel = 0;
  let inFrontmatter = false;
  let frontmatterPassed = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (i === 0 && line.trim() === "---") {
      inFrontmatter = true;
      continue;
    }
    if (inFrontmatter) {
      if (line.trim() === "---") {
        inFrontmatter = false;
        frontmatterPassed = true;
      }
      continue;
    }
    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (headingMatch) {
      const level = headingMatch[1].length;
      const headingText = headingMatch[2].trim().toLowerCase();
      if (capturing) {
        if (level <= captureLevel) {
          capturing = false;
        }
      }
      if (!capturing && lowerTargets.includes(headingText)) {
        capturing = true;
        captureLevel = level;
        continue;
      }
      if (capturing) {
        resultBlocks.push(line);
      }
      continue;
    }
    if (capturing) {
      if (/^\s*- \[[ xX]\]/.test(line)) {
        continue;
      }
      resultBlocks.push(line);
    }
  }
  while (resultBlocks.length > 0 && resultBlocks[resultBlocks.length - 1].trim() === "") {
    resultBlocks.pop();
  }
  return resultBlocks.join("\n");
}

// src/ui/components/PhaseNotePanel.ts
var PhaseNotePanel = class {
  constructor(parentEl, app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.expanded = this.getSettings().ui.notePanel.defaultExpanded;
    this.renderComponent = new import_obsidian3.Component();
    this.renderComponent.load();
    this.el = parentEl.createDiv({ cls: "tm-note-panel" });
    this.el.style.display = "none";
    this.headerEl = this.el.createDiv({ cls: "tm-note-panel-header" });
    const toggleEl = this.headerEl.createSpan({ cls: "tm-note-panel-toggle" });
    toggleEl.textContent = this.expanded ? "\u25BC" : "\u25B6";
    const titleEl = this.headerEl.createSpan({ cls: "tm-note-panel-title" });
    titleEl.textContent = "\u7B14\u8BB0\u5185\u5BB9";
    this.fileNameEl = this.headerEl.createSpan({ cls: "tm-note-panel-filename" });
    this.headerEl.addEventListener("click", (e) => {
      if (e.target.classList.contains("tm-note-panel-filename"))
        return;
      this.expanded = !this.expanded;
      toggleEl.textContent = this.expanded ? "\u25BC" : "\u25B6";
      this.bodyEl.style.display = this.expanded ? "block" : "none";
    });
    this.bodyEl = this.el.createDiv({ cls: "tm-note-panel-body" });
    this.bodyEl.style.display = this.expanded ? "block" : "none";
    this.contentEl = this.bodyEl.createDiv({ cls: "tm-note-panel-content" });
  }
  async update(phaseId, phases) {
    const settings = this.getSettings();
    if (!settings.ui.notePanel.enabled) {
      this.el.style.display = "none";
      return;
    }
    const phase = phases.find((p) => p.id === phaseId);
    if (!(phase == null ? void 0 : phase.noteFilePath)) {
      this.el.style.display = "none";
      return;
    }
    const file = this.app.vault.getAbstractFileByPath(phase.noteFilePath);
    if (!(file instanceof import_obsidian3.TFile)) {
      this.el.style.display = "none";
      return;
    }
    const rawContent = await this.app.vault.cachedRead(file);
    const markdown = extractNoteContent(rawContent, settings.ui.notePanel.headings);
    if (!markdown.trim()) {
      this.el.style.display = "none";
      return;
    }
    this.fileNameEl.textContent = file.basename;
    this.fileNameEl.title = `\u6253\u5F00 ${file.path}`;
    this.fileNameEl.onclick = (e) => {
      e.stopPropagation();
      this.app.workspace.openLinkText(file.path, "", false);
    };
    this.contentEl.empty();
    await import_obsidian3.MarkdownRenderer.render(
      this.app,
      markdown,
      this.contentEl,
      file.path,
      this.renderComponent
    );
    this.el.style.display = "block";
  }
  hide() {
    this.el.style.display = "none";
  }
  destroy() {
    this.renderComponent.unload();
    this.el.remove();
  }
};

// src/ui/components/TaskItem.ts
var TaskItem = class {
  constructor(container, task, app, tagManager, eventBus, dragDropManager, settings, collapseOptions) {
    this.container = container;
    this.task = task;
    this.app = app;
    this.tagManager = tagManager;
    this.eventBus = eventBus;
    this.dragDropManager = dragDropManager;
    this.settings = settings;
    this.collapseOptions = collapseOptions;
    this.el = container.createDiv({ cls: "tm-task-item" });
    if (task.completed) {
      this.el.classList.add("tm-task-completed");
    }
    this.render();
    this.dragDropManager.setupDraggable(this.el, task.id);
  }
  render() {
    var _a;
    const opts = this.collapseOptions;
    if (opts == null ? void 0 : opts.hasChildren) {
      const toggle = this.el.createSpan({ cls: "tm-task-collapse-toggle" });
      toggle.textContent = opts.isCollapsed ? "\u25B6" : "\u25BC";
      toggle.addEventListener("click", (e) => {
        var _a2;
        e.stopPropagation();
        (_a2 = opts.onToggleCollapse) == null ? void 0 : _a2.call(opts);
      });
    }
    const checkbox = this.el.createEl("input", {
      type: "checkbox",
      cls: "tm-task-checkbox"
    });
    checkbox.checked = this.task.completed;
    checkbox.addEventListener("change", async () => {
      const success = await this.tagManager.toggleTaskCompletion(this.task);
      if (success) {
        this.eventBus.emit("task-toggled", {
          taskId: this.task.id,
          completed: !this.task.completed
        });
      }
    });
    const textEl = this.el.createDiv({ cls: "tm-task-text" });
    textEl.textContent = this.task.text;
    if ((opts == null ? void 0 : opts.isCollapsed) && opts.childCount && opts.childCount > 0) {
      const badge = this.el.createSpan({ cls: "tm-task-child-count" });
      badge.textContent = `${opts.childCount}\u4E2A\u5B50\u4EFB\u52A1`;
    }
    if (this.settings.ui.showSourceFile) {
      const sourceEl = this.el.createDiv({ cls: "tm-task-source" });
      const fileName = (_a = this.task.filePath.split("/").pop()) != null ? _a : this.task.filePath;
      sourceEl.textContent = fileName;
      sourceEl.addEventListener("click", (e) => {
        e.stopPropagation();
        const file = this.app.vault.getAbstractFileByPath(this.task.filePath);
        if (file) {
          const leaf = this.app.workspace.getLeaf(false);
          leaf.openFile(file, {
            eState: { line: this.task.lineNumber }
          });
        }
      });
    }
  }
};

// src/ui/utils/TaskTreeBuilder.ts
function buildTaskForest(tasks) {
  const byFile = /* @__PURE__ */ new Map();
  for (const task of tasks) {
    let group = byFile.get(task.filePath);
    if (!group) {
      group = [];
      byFile.set(task.filePath, group);
    }
    group.push(task);
  }
  const roots = [];
  for (const fileTasks of byFile.values()) {
    fileTasks.sort((a, b) => a.lineNumber - b.lineNumber);
    const stack = [];
    for (const task of fileTasks) {
      const node = { task, children: [] };
      while (stack.length > 0 && stack[stack.length - 1].level >= task.indentLevel) {
        stack.pop();
      }
      if (stack.length > 0) {
        stack[stack.length - 1].node.children.push(node);
      } else {
        roots.push(node);
      }
      stack.push({ node, level: task.indentLevel });
    }
  }
  return roots;
}
function countDescendants(node) {
  let count = node.children.length;
  for (const child of node.children) {
    count += countDescendants(child);
  }
  return count;
}

// src/ui/components/QuadrantCell.ts
var QuadrantCell = class {
  constructor(container, quadrant, app, tagManager, eventBus, dragDropManager, settings) {
    this.container = container;
    this.quadrant = quadrant;
    this.app = app;
    this.tagManager = tagManager;
    this.eventBus = eventBus;
    this.dragDropManager = dragDropManager;
    this.settings = settings;
    const color = settings.ui.quadrantColors[quadrant];
    this.el = container.createDiv({ cls: `tm-quadrant tm-quadrant-${quadrant}` });
    this.el.style.setProperty("--tm-quadrant-color", color);
    const header = this.el.createDiv({ cls: "tm-quadrant-header" });
    const titleEl = header.createSpan({ cls: "tm-quadrant-title" });
    titleEl.textContent = settings.ui.quadrantLabels[quadrant];
    this.countEl = header.createSpan({ cls: "tm-quadrant-count" });
    this.countEl.textContent = "0";
    this.taskListEl = this.el.createDiv({ cls: "tm-task-list" });
    this.dragDropManager.setupDropZone(this.el, quadrant);
  }
  renderTasks(tasks, collapsedIds, onToggleCollapse) {
    this.taskListEl.empty();
    this.countEl.textContent = `${tasks.length}`;
    const forest = buildTaskForest(tasks);
    for (const node of forest) {
      this.renderNode(this.taskListEl, node, collapsedIds, onToggleCollapse);
    }
  }
  renderNode(container, node, collapsedIds, onToggleCollapse) {
    const hasChildren = node.children.length > 0;
    const isCollapsed = hasChildren && collapsedIds.has(node.task.id);
    const childCount = hasChildren ? countDescendants(node) : 0;
    new TaskItem(
      container,
      node.task,
      this.app,
      this.tagManager,
      this.eventBus,
      this.dragDropManager,
      this.settings,
      hasChildren ? {
        hasChildren: true,
        isCollapsed,
        childCount,
        onToggleCollapse: () => onToggleCollapse(node.task.id)
      } : void 0
    );
    if (hasChildren && !isCollapsed) {
      const childrenContainer = container.createDiv({ cls: "tm-task-children" });
      for (const child of node.children) {
        this.renderNode(childrenContainer, child, collapsedIds, onToggleCollapse);
      }
    }
  }
};

// src/ui/components/QuadrantGrid.ts
var QuadrantGrid = class {
  constructor(container, app, tagManager, eventBus, dragDropManager, settings) {
    this.container = container;
    this.app = app;
    this.tagManager = tagManager;
    this.eventBus = eventBus;
    this.dragDropManager = dragDropManager;
    this.settings = settings;
    this.cells = /* @__PURE__ */ new Map();
    this.collapsedTaskIds = /* @__PURE__ */ new Set();
    this.lastViewId = "";
    this.lastTasks = [];
    this.el = container.createDiv({ cls: "tm-quadrant-grid" });
    for (const code of QUADRANT_CODES) {
      const cell = new QuadrantCell(
        this.el,
        code,
        app,
        tagManager,
        eventBus,
        dragDropManager,
        settings
      );
      this.cells.set(code, cell);
    }
    this.unassignedEl = container.createDiv({ cls: "tm-unassigned-tray" });
    const header = this.unassignedEl.createDiv({ cls: "tm-unassigned-header" });
    header.createSpan({ cls: "tm-unassigned-title", text: "\u672A\u5206\u914D\u4EFB\u52A1" });
    this.unassignedCountEl = header.createSpan({ cls: "tm-quadrant-count", text: "0" });
    let collapsed = false;
    header.addEventListener("click", () => {
      collapsed = !collapsed;
      this.unassignedListEl.style.display = collapsed ? "none" : "block";
      header.classList.toggle("tm-collapsed", collapsed);
    });
    this.unassignedListEl = this.unassignedEl.createDiv({ cls: "tm-task-list" });
    this.dragDropManager.setupUnassignedDropZone(this.unassignedEl);
  }
  toggleCollapse(taskId) {
    if (this.collapsedTaskIds.has(taskId)) {
      this.collapsedTaskIds.delete(taskId);
    } else {
      this.collapsedTaskIds.add(taskId);
    }
    this.render(this.lastViewId, this.lastTasks);
  }
  /** Render tasks grouped by their quadrant assignment for a given viewId */
  render(viewId, tasks) {
    var _a;
    this.lastViewId = viewId;
    this.lastTasks = tasks;
    const grouped = {
      ui: [],
      in: [],
      un: [],
      nn: [],
      unassigned: []
    };
    for (const task of tasks) {
      const q = task.quadrantAssignments[viewId];
      if (q && grouped[q]) {
        grouped[q].push(task);
      } else {
        grouped.unassigned.push(task);
      }
    }
    const onToggle = (id) => this.toggleCollapse(id);
    for (const code of QUADRANT_CODES) {
      (_a = this.cells.get(code)) == null ? void 0 : _a.renderTasks(grouped[code], this.collapsedTaskIds, onToggle);
    }
    this.unassignedListEl.empty();
    this.unassignedCountEl.textContent = `${grouped.unassigned.length}`;
    const forest = buildTaskForest(grouped.unassigned);
    for (const node of forest) {
      this.renderUnassignedNode(this.unassignedListEl, node);
    }
  }
  renderUnassignedNode(container, node) {
    const hasChildren = node.children.length > 0;
    const isCollapsed = hasChildren && this.collapsedTaskIds.has(node.task.id);
    const childCount = hasChildren ? countDescendants(node) : 0;
    new TaskItem(
      container,
      node.task,
      this.app,
      this.tagManager,
      this.eventBus,
      this.dragDropManager,
      this.settings,
      hasChildren ? {
        hasChildren: true,
        isCollapsed,
        childCount,
        onToggleCollapse: () => this.toggleCollapse(node.task.id)
      } : void 0
    );
    if (hasChildren && !isCollapsed) {
      const childrenContainer = container.createDiv({ cls: "tm-task-children" });
      for (const child of node.children) {
        this.renderUnassignedNode(childrenContainer, child);
      }
    }
  }
};

// src/ui/components/CreatePhaseModal.ts
var import_obsidian4 = require("obsidian");
var CreatePhaseModal = class extends import_obsidian4.Modal {
  constructor(app, existingPhases, onSubmit, targetFileName, prefill) {
    super(app);
    this.existingPhases = existingPhases;
    this.onSubmit = onSubmit;
    this.targetFileName = targetFileName;
    this.prefill = prefill;
    this.phaseId = "";
    this.phaseLabel = "";
    this.phaseStart = "";
    this.phaseEnd = "";
    this.selectedExistingPhaseId = "";
    this.mode = "select";
  }
  onOpen() {
    var _a, _b, _c, _d;
    const { contentEl } = this;
    contentEl.empty();
    if (this.prefill) {
      this.mode = "complete";
      this.phaseId = (_a = this.prefill.phaseId) != null ? _a : "";
      this.phaseLabel = (_b = this.prefill.phaseLabel) != null ? _b : "";
      this.phaseStart = (_c = this.prefill.phaseStart) != null ? _c : "";
      this.phaseEnd = (_d = this.prefill.phaseEnd) != null ? _d : "";
      contentEl.createEl("h3", { text: "\u8865\u5168\u9636\u6BB5\u5C5E\u6027" });
      if (this.targetFileName) {
        contentEl.createEl("p", {
          text: `\u76EE\u6807\u7B14\u8BB0: ${this.targetFileName}`,
          cls: "setting-item-description"
        });
      }
      this.renderCompleteForm(contentEl);
      return;
    }
    contentEl.createEl("h3", { text: "\u6DFB\u52A0\u9636\u6BB5\u5C5E\u6027" });
    if (this.targetFileName) {
      contentEl.createEl("p", {
        text: `\u76EE\u6807\u7B14\u8BB0: ${this.targetFileName}`,
        cls: "setting-item-description"
      });
    }
    if (this.existingPhases.length > 0) {
      this.renderModeSelector(contentEl);
    } else {
      this.mode = "create";
      this.renderCreateForm(contentEl);
      new import_obsidian4.Setting(contentEl).addButton(
        (btn) => btn.setButtonText("\u521B\u5EFA").setCta().onClick(() => this.handleSubmit())
      );
    }
  }
  renderModeSelector(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("\u64CD\u4F5C\u7C7B\u578B").addDropdown((dropdown) => {
      dropdown.addOption("select", "\u9009\u62E9\u5DF2\u6709\u9636\u6BB5");
      dropdown.addOption("create", "\u521B\u5EFA\u65B0\u9636\u6BB5");
      dropdown.setValue(this.mode);
      dropdown.onChange((value) => {
        this.mode = value;
        const formContainer2 = containerEl.querySelector(".tm-phase-form-container");
        if (formContainer2) {
          formContainer2.empty();
          if (this.mode === "select") {
            this.renderSelectForm(formContainer2);
          } else {
            this.renderCreateForm(formContainer2);
          }
        }
      });
    });
    const formContainer = containerEl.createDiv({ cls: "tm-phase-form-container" });
    this.renderSelectForm(formContainer);
    new import_obsidian4.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("\u6DFB\u52A0").setCta().onClick(() => this.handleSubmit())
    );
  }
  renderSelectForm(containerEl) {
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("\u9009\u62E9\u9636\u6BB5").setDesc("\u5C06\u6B64\u7B14\u8BB0\u5173\u8054\u5230\u5DF2\u5B58\u5728\u7684\u9636\u6BB5").addDropdown((dropdown) => {
      dropdown.addOption("", "-- \u8BF7\u9009\u62E9\u9636\u6BB5 --");
      const sortedPhases = [...this.existingPhases].sort((a, b) => a.order - b.order);
      for (const phase of sortedPhases) {
        dropdown.addOption(phase.id, `${phase.label} (${phase.id})`);
      }
      dropdown.setValue(this.selectedExistingPhaseId);
      dropdown.onChange((value) => {
        this.selectedExistingPhaseId = value;
        const selectedPhase = this.existingPhases.find((p) => p.id === value);
        if (selectedPhase) {
          this.phaseLabel = selectedPhase.label;
        }
      });
    });
  }
  renderCreateForm(containerEl) {
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("\u9636\u6BB5 ID").setDesc("\u5B57\u6BCD\u5F00\u5934\uFF0C\u652F\u6301\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u4E0B\u5212\u7EBF\uFF0C\u5982 mvp").addText(
      (text) => text.setPlaceholder("mvp").onChange((v) => {
        this.phaseId = v.trim();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u663E\u793A\u540D\u79F0").addText(
      (text) => text.setPlaceholder("MVP\u9636\u6BB5").onChange((v) => {
        this.phaseLabel = v.trim();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u5F00\u59CB\u65E5\u671F").setDesc("\u683C\u5F0F: YYYY-MM-DD\uFF0C\u53EF\u7559\u7A7A").addText(
      (text) => text.setPlaceholder("2025-01-01").onChange((v) => {
        this.phaseStart = v.trim();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u7ED3\u675F\u65E5\u671F").setDesc("\u683C\u5F0F: YYYY-MM-DD\uFF0C\u53EF\u7559\u7A7A").addText(
      (text) => text.setPlaceholder("2025-06-30").onChange((v) => {
        this.phaseEnd = v.trim();
      })
    );
  }
  renderCompleteForm(containerEl) {
    var _a, _b, _c, _d;
    const hasMissingId = !((_a = this.prefill) == null ? void 0 : _a.phaseId);
    const hasMissingLabel = !((_b = this.prefill) == null ? void 0 : _b.phaseLabel);
    const hasMissingStart = !((_c = this.prefill) == null ? void 0 : _c.phaseStart);
    const hasMissingEnd = !((_d = this.prefill) == null ? void 0 : _d.phaseEnd);
    containerEl.createEl("p", {
      text: "\u8BE5\u7B14\u8BB0\u5DF2\u6807\u8BB0\u4E3A\u9636\u6BB5\u7B14\u8BB0\uFF0C\u4F46\u7F3A\u5C11\u90E8\u5206\u5C5E\u6027\u3002\u8BF7\u8865\u5168\u4EE5\u4E0B\u4FE1\u606F:",
      cls: "setting-item-description"
    });
    if (hasMissingId) {
      new import_obsidian4.Setting(containerEl).setName("\u9636\u6BB5 ID").setDesc("\u5B57\u6BCD\u5F00\u5934\uFF0C\u652F\u6301\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u4E0B\u5212\u7EBF").addText(
        (text) => text.setPlaceholder("mvp").setValue(this.phaseId).onChange((v) => {
          this.phaseId = v.trim();
        })
      );
    } else {
      new import_obsidian4.Setting(containerEl).setName("\u9636\u6BB5 ID").setDesc(this.phaseId);
    }
    if (hasMissingLabel) {
      new import_obsidian4.Setting(containerEl).setName("\u663E\u793A\u540D\u79F0").addText(
        (text) => text.setPlaceholder("MVP\u9636\u6BB5").setValue(this.phaseLabel).onChange((v) => {
          this.phaseLabel = v.trim();
        })
      );
    } else {
      new import_obsidian4.Setting(containerEl).setName("\u663E\u793A\u540D\u79F0").setDesc(this.phaseLabel);
    }
    if (hasMissingStart) {
      new import_obsidian4.Setting(containerEl).setName("\u5F00\u59CB\u65E5\u671F").setDesc("\u683C\u5F0F: YYYY-MM-DD\uFF0C\u53EF\u7559\u7A7A").addText(
        (text) => text.setPlaceholder("2025-01-01").setValue(this.phaseStart).onChange((v) => {
          this.phaseStart = v.trim();
        })
      );
    } else {
      new import_obsidian4.Setting(containerEl).setName("\u5F00\u59CB\u65E5\u671F").setDesc(this.phaseStart);
    }
    if (hasMissingEnd) {
      new import_obsidian4.Setting(containerEl).setName("\u7ED3\u675F\u65E5\u671F").setDesc("\u683C\u5F0F: YYYY-MM-DD\uFF0C\u53EF\u7559\u7A7A").addText(
        (text) => text.setPlaceholder("2025-06-30").setValue(this.phaseEnd).onChange((v) => {
          this.phaseEnd = v.trim();
        })
      );
    } else {
      new import_obsidian4.Setting(containerEl).setName("\u7ED3\u675F\u65E5\u671F").setDesc(this.phaseEnd);
    }
    new import_obsidian4.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("\u8865\u5168\u5C5E\u6027").setCta().onClick(() => this.handleSubmit())
    );
  }
  handleSubmit() {
    if (this.mode === "select") {
      if (!this.selectedExistingPhaseId) {
        new import_obsidian4.Notice("\u8BF7\u9009\u62E9\u4E00\u4E2A\u9636\u6BB5");
        return;
      }
      const selectedPhase = this.existingPhases.find((p) => p.id === this.selectedExistingPhaseId);
      if (selectedPhase) {
        this.onSubmit(selectedPhase.id, selectedPhase.label, "", "");
        this.close();
      }
    } else if (this.mode === "create") {
      if (!this.phaseId || !this.phaseLabel) {
        new import_obsidian4.Notice("\u8BF7\u8F93\u5165\u9636\u6BB5 ID \u548C\u663E\u793A\u540D\u79F0");
        return;
      }
      if (this.phaseStart && !/^\d{4}-\d{2}-\d{2}$/.test(this.phaseStart)) {
        new import_obsidian4.Notice("\u5F00\u59CB\u65E5\u671F\u683C\u5F0F\u65E0\u6548\uFF0C\u8BF7\u4F7F\u7528 YYYY-MM-DD \u683C\u5F0F");
        return;
      }
      if (this.phaseEnd && !/^\d{4}-\d{2}-\d{2}$/.test(this.phaseEnd)) {
        new import_obsidian4.Notice("\u7ED3\u675F\u65E5\u671F\u683C\u5F0F\u65E0\u6548\uFF0C\u8BF7\u4F7F\u7528 YYYY-MM-DD \u683C\u5F0F");
        return;
      }
      this.onSubmit(this.phaseId, this.phaseLabel, this.phaseStart, this.phaseEnd);
      this.close();
    } else {
      if (!this.phaseId) {
        new import_obsidian4.Notice("\u8BF7\u8F93\u5165\u9636\u6BB5 ID");
        return;
      }
      if (!this.phaseLabel) {
        new import_obsidian4.Notice("\u8BF7\u8F93\u5165\u663E\u793A\u540D\u79F0");
        return;
      }
      if (this.phaseStart && !/^\d{4}-\d{2}-\d{2}$/.test(this.phaseStart)) {
        new import_obsidian4.Notice("\u5F00\u59CB\u65E5\u671F\u683C\u5F0F\u65E0\u6548\uFF0C\u8BF7\u4F7F\u7528 YYYY-MM-DD \u683C\u5F0F");
        return;
      }
      if (this.phaseEnd && !/^\d{4}-\d{2}-\d{2}$/.test(this.phaseEnd)) {
        new import_obsidian4.Notice("\u7ED3\u675F\u65E5\u671F\u683C\u5F0F\u65E0\u6548\uFF0C\u8BF7\u4F7F\u7528 YYYY-MM-DD \u683C\u5F0F");
        return;
      }
      this.onSubmit(this.phaseId, this.phaseLabel, this.phaseStart, this.phaseEnd);
      this.close();
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/components/TimelineOverview.ts
var TIMELINE_COLORS = [
  "#3498db",
  "#e74c3c",
  "#2ecc71",
  "#f39c12",
  "#9b59b6",
  "#1abc9c",
  "#e67e22",
  "#34495e"
];
var TimelineOverview = class {
  constructor(container, getSettings, eventBus) {
    this.getSettings = getSettings;
    this.eventBus = eventBus;
    this.headerRangeEl = null;
    this.bodyEl = null;
    this.el = container.createDiv({ cls: "tm-timeline-container" });
    this.el.style.display = "none";
  }
  show() {
    this.el.style.display = "flex";
  }
  hide() {
    this.el.style.display = "none";
  }
  render(phases) {
    this.el.empty();
    const header = this.el.createDiv({ cls: "tm-timeline-header" });
    header.createSpan({ cls: "tm-timeline-title", text: "\u9879\u76EE\u65F6\u95F4\u8F74" });
    this.headerRangeEl = header.createSpan({ cls: "tm-timeline-range" });
    this.bodyEl = this.el.createDiv({ cls: "tm-timeline-body" });
    const validPhases = phases.filter((p) => p.timePeriod && this.parseDate(p.timePeriod.start) && this.parseDate(p.timePeriod.end)).sort((a, b) => a.order - b.order);
    if (validPhases.length === 0) {
      this.renderEmpty();
      return;
    }
    let projectStart = null;
    let projectEnd = null;
    for (const p of validPhases) {
      const s = this.parseDate(p.timePeriod.start);
      const e = this.parseDate(p.timePeriod.end);
      if (!projectStart || s < projectStart)
        projectStart = s;
      if (!projectEnd || e > projectEnd)
        projectEnd = e;
    }
    if (!projectStart || !projectEnd) {
      this.renderEmpty();
      return;
    }
    const totalDays = this.daysBetween(projectStart, projectEnd);
    if (totalDays <= 0) {
      this.headerRangeEl.textContent = this.formatDate(projectStart);
    } else {
      this.headerRangeEl.textContent = `${this.formatDate(projectStart)} \u2014 ${this.formatDate(projectEnd)}`;
    }
    const today = /* @__PURE__ */ new Date();
    today.setHours(0, 0, 0, 0);
    const todayPct = totalDays > 0 ? this.daysBetween(projectStart, today) / totalDays * 100 : -1;
    const rows = this.bodyEl.createDiv({ cls: "tm-timeline-rows" });
    for (let i = 0; i < validPhases.length; i++) {
      const phase = validPhases[i];
      const phaseStart = this.parseDate(phase.timePeriod.start);
      const phaseEnd = this.parseDate(phase.timePeriod.end);
      const color = TIMELINE_COLORS[i % TIMELINE_COLORS.length];
      const leftPct = totalDays > 0 ? this.daysBetween(projectStart, phaseStart) / totalDays * 100 : 0;
      const widthPct = totalDays > 0 ? this.daysBetween(phaseStart, phaseEnd) / totalDays * 100 : 100;
      const row = rows.createDiv({ cls: "tm-timeline-row" });
      const label = row.createSpan({ cls: "tm-timeline-row-label", text: phase.label });
      label.title = phase.label;
      row.createSpan({ cls: "tm-timeline-row-date", text: phase.timePeriod.start });
      const track = row.createDiv({ cls: "tm-timeline-row-track" });
      const bar = track.createDiv({ cls: "tm-timeline-row-bar" });
      bar.style.left = `${Math.max(0, leftPct)}%`;
      bar.style.width = `${Math.max(0.5, widthPct)}%`;
      bar.style.background = color;
      if (todayPct >= 0 && todayPct <= 100) {
        const cursor = track.createDiv({ cls: "tm-timeline-today-cursor" });
        cursor.style.left = `${todayPct}%`;
        if (i === 0) {
          const cursorLabel = cursor.createDiv({ cls: "tm-timeline-today-cursor-label" });
          cursorLabel.textContent = "\u4ECA\u5929";
        }
      }
      row.createSpan({ cls: "tm-timeline-row-date", text: phase.timePeriod.end });
      row.addEventListener("click", () => {
        this.eventBus.emit("timeline-toggled", { active: false });
        this.eventBus.emit("view-switched", { viewId: phase.id, viewType: "phase" });
      });
    }
  }
  destroy() {
    this.el.remove();
  }
  renderEmpty() {
    if (!this.bodyEl)
      return;
    this.headerRangeEl.textContent = "";
    const empty = this.bodyEl.createDiv({ cls: "tm-timeline-empty" });
    empty.textContent = "\u6682\u65E0\u9636\u6BB5\u914D\u7F6E\u4E86\u65F6\u95F4\u8303\u56F4\u3002\u8BF7\u5728\u9636\u6BB5\u7B14\u8BB0\u7684 frontmatter \u4E2D\u6DFB\u52A0 phase-start \u548C phase-end \u5C5E\u6027\u3002";
  }
  parseDate(str) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(str))
      return null;
    const [y, m, d] = str.split("-").map(Number);
    const date = new Date(y, m - 1, d);
    if (isNaN(date.getTime()))
      return null;
    return date;
  }
  daysBetween(a, b) {
    return Math.round((b.getTime() - a.getTime()) / (1e3 * 60 * 60 * 24));
  }
  formatDate(d) {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
};

// src/ui/components/InlineTimeline.ts
var TIMELINE_COLORS2 = [
  "#3498db",
  "#e74c3c",
  "#2ecc71",
  "#f39c12",
  "#9b59b6",
  "#1abc9c",
  "#e67e22",
  "#34495e"
];
var InlineTimeline = class {
  constructor(container, getSettings, eventBus) {
    this.getSettings = getSettings;
    this.eventBus = eventBus;
    this.el = container.createDiv({ cls: "tm-inline-timeline" });
    this.el.style.display = "none";
  }
  show() {
    this.el.style.display = "flex";
  }
  hide() {
    this.el.style.display = "none";
  }
  render(currentPhaseId) {
    this.el.empty();
    const phases = this.getSettings().phases;
    const phase = phases.find((p) => p.id === currentPhaseId);
    if (!phase || !phase.timePeriod) {
      this.el.style.display = "none";
      return;
    }
    const start = this.parseDate(phase.timePeriod.start);
    const end = this.parseDate(phase.timePeriod.end);
    if (!start || !end) {
      this.el.style.display = "none";
      return;
    }
    this.el.style.display = "flex";
    const totalDays = this.daysBetween(start, end);
    const sortedPhases = [...phases].filter((p) => p.timePeriod && this.parseDate(p.timePeriod.start) && this.parseDate(p.timePeriod.end)).sort((a, b) => a.order - b.order);
    const colorIndex = sortedPhases.findIndex((p) => p.id === currentPhaseId);
    const color = TIMELINE_COLORS2[(colorIndex >= 0 ? colorIndex : 0) % TIMELINE_COLORS2.length];
    this.el.createSpan({ cls: "tm-inline-timeline-date", text: phase.timePeriod.start });
    const track = this.el.createDiv({ cls: "tm-inline-timeline-track" });
    const bar = track.createDiv({ cls: "tm-inline-timeline-bar" });
    bar.style.background = color;
    if (totalDays > 0) {
      const today = /* @__PURE__ */ new Date();
      today.setHours(0, 0, 0, 0);
      const todayPct = this.daysBetween(start, today) / totalDays * 100;
      if (todayPct >= 0 && todayPct <= 100) {
        const cursor = track.createDiv({ cls: "tm-inline-timeline-cursor" });
        cursor.style.left = `${todayPct}%`;
        const cursorLabel = cursor.createDiv({ cls: "tm-inline-timeline-cursor-label" });
        cursorLabel.textContent = "\u4ECA\u5929";
      }
    }
    this.el.createSpan({ cls: "tm-inline-timeline-date", text: phase.timePeriod.end });
  }
  destroy() {
    this.el.remove();
  }
  parseDate(str) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(str))
      return null;
    const [y, m, d] = str.split("-").map(Number);
    const date = new Date(y, m - 1, d);
    if (isNaN(date.getTime()))
      return null;
    return date;
  }
  daysBetween(a, b) {
    return Math.round((b.getTime() - a.getTime()) / (1e3 * 60 * 60 * 24));
  }
};

// src/ui/MatrixView.ts
var MatrixView = class extends import_obsidian5.ItemView {
  constructor(leaf, eventBus, taskScanner, tagManager, viewRegistry, getSettings, onAddPhaseToNote, onCompletePhaseNote) {
    super(leaf);
    this.eventBus = eventBus;
    this.taskScanner = taskScanner;
    this.tagManager = tagManager;
    this.viewRegistry = viewRegistry;
    this.getSettings = getSettings;
    this.onAddPhaseToNote = onAddPhaseToNote;
    this.onCompletePhaseNote = onCompletePhaseNote;
    this.currentViewId = "";
    this.timelineActive = false;
    this.navigator = null;
    this.phaseNotePanel = null;
    this.quadrantGrid = null;
    this.timelineOverview = null;
    this.inlineTimeline = null;
    // Refresh/progress elements (hosted inside navigator)
    this.refreshBtn = null;
    this.progressWrapEl = null;
    this.progressFillEl = null;
    this.progressTextEl = null;
    this.dragDropManager = new DragDropManager(
      this.app,
      this.tagManager,
      this.eventBus,
      () => this.currentViewId,
      (id) => this.taskScanner.getAllTasks().find((t) => t.id === id)
    );
    this.onScanComplete = () => {
      this.hideProgress();
      this.refresh();
    };
    this.onScanProgress = (p) => this.updateProgress(p.scanned, p.total);
    this.onTasksChanged = () => this.refresh();
    this.onTaskUpdated = () => this.refresh();
    this.onTaskToggled = () => this.refresh();
    this.onViewSwitched = (p) => this.switchView(p.viewId);
    this.onSettingsChanged = () => this.rebuildUI();
    this.onTimelineToggled = (p) => this.toggleTimeline(p.active);
  }
  getViewType() {
    return VIEW_TYPE_MATRIX;
  }
  getDisplayText() {
    return "Task Maker";
  }
  getIcon() {
    return "layout-grid";
  }
  async onOpen() {
    this.eventBus.on("scan-complete", this.onScanComplete);
    this.eventBus.on("scan-progress", this.onScanProgress);
    this.eventBus.on("tasks-changed", this.onTasksChanged);
    this.eventBus.on("task-updated", this.onTaskUpdated);
    this.eventBus.on("task-toggled", this.onTaskToggled);
    this.eventBus.on("view-switched", this.onViewSwitched);
    this.eventBus.on("settings-changed", this.onSettingsChanged);
    this.eventBus.on("timeline-toggled", this.onTimelineToggled);
    this.buildUI();
    const phases = this.viewRegistry.getPhaseViews();
    if (phases.length > 0) {
      this.switchView(phases[0].id);
    }
  }
  async onClose() {
    var _a, _b, _c;
    (_a = this.phaseNotePanel) == null ? void 0 : _a.destroy();
    (_b = this.timelineOverview) == null ? void 0 : _b.destroy();
    (_c = this.inlineTimeline) == null ? void 0 : _c.destroy();
    this.eventBus.off("scan-complete", this.onScanComplete);
    this.eventBus.off("scan-progress", this.onScanProgress);
    this.eventBus.off("tasks-changed", this.onTasksChanged);
    this.eventBus.off("task-updated", this.onTaskUpdated);
    this.eventBus.off("task-toggled", this.onTaskToggled);
    this.eventBus.off("view-switched", this.onViewSwitched);
    this.eventBus.off("settings-changed", this.onSettingsChanged);
    this.eventBus.off("timeline-toggled", this.onTimelineToggled);
  }
  buildUI() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.classList.add("task-maker-container");
    const settings = this.getSettings();
    this.navigator = new ViewNavigator(
      contentEl,
      this.viewRegistry,
      this.eventBus,
      this.onAddPhaseToNote ? () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          new import_obsidian5.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
          return;
        }
        if (activeFile.extension !== "md") {
          new import_obsidian5.Notice("\u5F53\u524D\u6587\u4EF6\u4E0D\u662F Markdown \u7B14\u8BB0");
          return;
        }
        const cache = this.app.metadataCache.getFileCache(activeFile);
        const fm = cache == null ? void 0 : cache.frontmatter;
        const isPhaseNote = (fm == null ? void 0 : fm["phase"]) === true || (fm == null ? void 0 : fm["phase"]) === "true";
        if (isPhaseNote) {
          const existingId = typeof (fm == null ? void 0 : fm["phase-id"]) === "string" ? fm["phase-id"].trim() : "";
          const existingLabel = typeof (fm == null ? void 0 : fm["phase-label"]) === "string" ? fm["phase-label"].trim() : "";
          const existingStart = typeof (fm == null ? void 0 : fm["phase-start"]) === "string" ? fm["phase-start"].trim() : "";
          const existingEnd = typeof (fm == null ? void 0 : fm["phase-end"]) === "string" ? fm["phase-end"].trim() : "";
          const hasAllRequired = existingId && existingLabel;
          const hasAllDates = existingStart && existingEnd;
          if (hasAllRequired && hasAllDates) {
            new import_obsidian5.Notice(`\u8BE5\u7B14\u8BB0\u5DF2\u7ECF\u662F\u5B8C\u6574\u7684\u9636\u6BB5\u7B14\u8BB0 (${activeFile.basename})`);
            return;
          }
          const capturedFile2 = activeFile;
          const prefill = {
            phaseId: existingId || void 0,
            phaseLabel: existingLabel || void 0,
            phaseStart: existingStart || void 0,
            phaseEnd: existingEnd || void 0
          };
          new CreatePhaseModal(
            this.app,
            this.getSettings().phases,
            (id, label, start, end) => {
              var _a;
              (_a = this.onCompletePhaseNote) == null ? void 0 : _a.call(this, capturedFile2, id, label, start, end);
            },
            capturedFile2.basename,
            prefill
          ).open();
          return;
        }
        const capturedFile = activeFile;
        new CreatePhaseModal(this.app, this.getSettings().phases, (id, label, start, end) => {
          this.onAddPhaseToNote(capturedFile, id, label, start, end);
        }, capturedFile.basename).open();
      } : void 0,
      () => this.refresh()
    );
    const scanHost = this.navigator.getScanHost();
    this.refreshBtn = scanHost.createEl("button", { cls: "tm-refresh-btn" });
    this.refreshBtn.textContent = "\u626B\u63CF\u4EFB\u52A1";
    this.refreshBtn.addEventListener("click", async () => {
      this.refreshBtn.disabled = true;
      this.refreshBtn.textContent = "\u626B\u63CF\u4E2D\u2026";
      await this.taskScanner.fullScan();
      this.refreshBtn.disabled = false;
      this.refreshBtn.textContent = "\u626B\u63CF\u4EFB\u52A1";
    });
    this.progressWrapEl = scanHost.createDiv({ cls: "tm-progress-wrap" });
    this.progressWrapEl.style.display = "none";
    const progressBarEl = this.progressWrapEl.createDiv({ cls: "tm-progress-bar" });
    this.progressFillEl = progressBarEl.createDiv({ cls: "tm-progress-fill" });
    this.progressTextEl = this.progressWrapEl.createDiv({ cls: "tm-progress-text" });
    this.inlineTimeline = new InlineTimeline(contentEl, this.getSettings, this.eventBus);
    this.phaseNotePanel = new PhaseNotePanel(contentEl, this.app, this.getSettings);
    this.quadrantGrid = new QuadrantGrid(
      contentEl,
      this.app,
      this.tagManager,
      this.eventBus,
      this.dragDropManager,
      settings
    );
    this.timelineOverview = new TimelineOverview(contentEl, this.getSettings, this.eventBus);
  }
  rebuildUI() {
    var _a, _b, _c;
    (_a = this.phaseNotePanel) == null ? void 0 : _a.destroy();
    (_b = this.timelineOverview) == null ? void 0 : _b.destroy();
    (_c = this.inlineTimeline) == null ? void 0 : _c.destroy();
    this.buildUI();
    if (this.timelineActive) {
      this.toggleTimeline(true);
    } else {
      this.switchView(this.currentViewId);
    }
  }
  switchView(viewId) {
    var _a, _b, _c, _d, _e, _f;
    this.currentViewId = viewId;
    (_a = this.navigator) == null ? void 0 : _a.updatePhaseView(viewId);
    if (this.timelineActive) {
      this.timelineActive = false;
      (_b = this.navigator) == null ? void 0 : _b.setTimelineActive(false);
      if ((_c = this.inlineTimeline) == null ? void 0 : _c.el)
        this.inlineTimeline.el.style.display = "";
      if ((_d = this.phaseNotePanel) == null ? void 0 : _d.el)
        this.phaseNotePanel.el.style.display = "";
      if ((_e = this.quadrantGrid) == null ? void 0 : _e.el)
        this.quadrantGrid.el.style.display = "";
      const unassignedEl = this.contentEl.querySelector(".tm-unassigned-tray");
      if (unassignedEl)
        unassignedEl.style.display = "";
      (_f = this.timelineOverview) == null ? void 0 : _f.hide();
    }
    this.refresh();
  }
  toggleTimeline(active) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    this.timelineActive = active;
    const unassignedEl = this.contentEl.querySelector(".tm-unassigned-tray");
    if (active) {
      if ((_a = this.inlineTimeline) == null ? void 0 : _a.el)
        this.inlineTimeline.el.style.display = "none";
      if ((_b = this.phaseNotePanel) == null ? void 0 : _b.el)
        this.phaseNotePanel.el.style.display = "none";
      if ((_c = this.quadrantGrid) == null ? void 0 : _c.el)
        this.quadrantGrid.el.style.display = "none";
      if (unassignedEl)
        unassignedEl.style.display = "none";
      (_d = this.timelineOverview) == null ? void 0 : _d.show();
      (_e = this.timelineOverview) == null ? void 0 : _e.render(this.getSettings().phases);
    } else {
      (_f = this.timelineOverview) == null ? void 0 : _f.hide();
      if ((_g = this.inlineTimeline) == null ? void 0 : _g.el)
        this.inlineTimeline.el.style.display = "";
      if ((_h = this.phaseNotePanel) == null ? void 0 : _h.el)
        this.phaseNotePanel.el.style.display = "";
      if ((_i = this.quadrantGrid) == null ? void 0 : _i.el)
        this.quadrantGrid.el.style.display = "";
      if (unassignedEl)
        unassignedEl.style.display = "";
      this.refresh();
    }
  }
  async refresh() {
    var _a, _b, _c, _d, _e;
    if (!this.currentViewId)
      return;
    if (this.timelineActive) {
      (_a = this.timelineOverview) == null ? void 0 : _a.render(this.getSettings().phases);
      return;
    }
    const settings = this.getSettings();
    const noteToPhase = /* @__PURE__ */ new Map();
    for (const phase of settings.phases) {
      if (phase.noteFilePath) {
        noteToPhase.set(phase.noteFilePath, phase.id);
      }
    }
    const allTasks = this.taskScanner.getAllTasks();
    let gridTasks = allTasks.filter((task) => {
      if (task.quadrantAssignments[this.currentViewId])
        return true;
      if (noteToPhase.get(task.filePath) === this.currentViewId)
        return true;
      return false;
    });
    if ((_b = this.navigator) == null ? void 0 : _b.isHideCompleted()) {
      gridTasks = gridTasks.filter((t) => !t.completed);
    }
    (_c = this.quadrantGrid) == null ? void 0 : _c.render(this.currentViewId, gridTasks);
    (_d = this.inlineTimeline) == null ? void 0 : _d.render(this.currentViewId);
    await ((_e = this.phaseNotePanel) == null ? void 0 : _e.update(this.currentViewId, settings.phases));
  }
  updateProgress(scanned, total) {
    if (!this.progressWrapEl || !this.progressFillEl || !this.progressTextEl)
      return;
    this.progressWrapEl.style.display = "flex";
    const pct = total > 0 ? Math.round(scanned / total * 100) : 0;
    this.progressFillEl.style.width = `${pct}%`;
    this.progressTextEl.textContent = `${scanned} / ${total} \u6587\u4EF6 (${pct}%)`;
  }
  hideProgress() {
    if (!this.progressWrapEl || !this.progressFillEl || !this.progressTextEl)
      return;
    this.progressFillEl.style.width = "100%";
    this.progressTextEl.textContent = "\u626B\u63CF\u5B8C\u6210";
    setTimeout(() => {
      if (this.progressWrapEl)
        this.progressWrapEl.style.display = "none";
    }, 800);
  }
};

// src/settings/SettingsTab.ts
var import_obsidian6 = require("obsidian");
var SettingsTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin, viewRegistry, eventBus) {
    super(app, plugin);
    this.plugin = plugin;
    this.viewRegistry = viewRegistry;
    this.eventBus = eventBus;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const settings = this.plugin.settings;
    containerEl.createEl("h2", { text: "\u4EFB\u52A1\u89E6\u53D1\u6807\u7B7E" });
    new import_obsidian6.Setting(containerEl).setName("\u89E6\u53D1\u6807\u7B7E").setDesc("\u5305\u542B\u8FD9\u4E9B\u6807\u7B7E\u7684\u7B14\u8BB0\u6216\u4EFB\u52A1\u884C\u5C06\u88AB\u63D0\u53D6\u3002\u7528\u9017\u53F7\u5206\u9694\uFF0C\u4E0D\u542B # \u53F7\u3002").addText(
      (text) => text.setPlaceholder("task, todo").setValue(settings.triggerTags.join(", ")).onChange(async (value) => {
        settings.triggerTags = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6807\u7B7E\u547D\u540D\u7A7A\u95F4").setDesc("\u63D2\u4EF6\u521B\u5EFA\u7684\u8C61\u9650\u6807\u7B7E\u5C06\u5D4C\u5957\u5728\u6B64\u547D\u540D\u7A7A\u95F4\u4E0B\uFF0C\u5982\u8BBE\u4E3A T \u5219\u6807\u7B7E\u683C\u5F0F\u4E3A #T/viewId-quadrant\u3002\u7559\u7A7A\u5219\u4E0D\u52A0\u524D\u7F00\u3002").addText(
      (text) => text.setPlaceholder("T").setValue(settings.tagNamespace).onChange(async (value) => {
        settings.tagNamespace = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u9636\u6BB5\u7BA1\u7406" });
    new import_obsidian6.Setting(containerEl).setName("\u4E00\u952E\u521B\u5EFA\u9636\u6BB5\u7B14\u8BB0").setDesc("\u521B\u5EFA\u5E26\u6709\u6B63\u786E frontmatter \u7684\u9636\u6BB5\u89C4\u5212\u7B14\u8BB0").addButton(
      (btn) => btn.setButtonText("\u65B0\u5EFA\u9636\u6BB5\u7B14\u8BB0").setCta().onClick(() => {
        new CreatePhaseModal(this.app, [], async (id, label, start, end) => {
          await this.plugin.createPhaseNote(id, label, start, end);
          this.display();
        }).open();
      })
    );
    this.renderPhaseList(containerEl, settings);
    containerEl.createEl("h2", { text: "\u754C\u9762\u5B9A\u5236" });
    const quadrantCodes = ["ui", "in", "un", "nn"];
    const defaultLabels = ["\u7D27\u6025\u4E14\u91CD\u8981", "\u91CD\u8981\u4E0D\u7D27\u6025", "\u7D27\u6025\u4E0D\u91CD\u8981", "\u4E0D\u7D27\u6025\u4E0D\u91CD\u8981"];
    for (let i = 0; i < quadrantCodes.length; i++) {
      const code = quadrantCodes[i];
      new import_obsidian6.Setting(containerEl).setName(`${defaultLabels[i]} \u6807\u7B7E`).addText(
        (text) => text.setValue(settings.ui.quadrantLabels[code]).onChange(async (value) => {
          settings.ui.quadrantLabels[code] = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian6.Setting(containerEl).setName("\u663E\u793A\u6765\u6E90\u6587\u4EF6").addToggle(
      (toggle) => toggle.setValue(settings.ui.showSourceFile).onChange(async (value) => {
        settings.ui.showSourceFile = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u7D27\u51D1\u6A21\u5F0F").addToggle(
      (toggle) => toggle.setValue(settings.ui.compactMode).onChange(async (value) => {
        settings.ui.compactMode = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u7B14\u8BB0\u5185\u5BB9\u9762\u677F" });
    new import_obsidian6.Setting(containerEl).setName("\u542F\u7528\u7B14\u8BB0\u5185\u5BB9\u9762\u677F").setDesc("\u5728\u8C61\u9650\u77E9\u9635\u4E0A\u65B9\u663E\u793A\u9636\u6BB5\u7B14\u8BB0\u4E2D\u7279\u5B9A\u6807\u9898\u4E0B\u7684\u5185\u5BB9").addToggle(
      (toggle) => toggle.setValue(settings.ui.notePanel.enabled).onChange(async (value) => {
        settings.ui.notePanel.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u63D0\u53D6\u6807\u9898").setDesc("\u4ECE\u8FD9\u4E9B\u6807\u9898\u4E0B\u63D0\u53D6\u5185\u5BB9\u663E\u793A\u5728\u9762\u677F\u4E2D\uFF0C\u7528\u9017\u53F7\u5206\u9694\u3002").addText(
      (text) => text.setPlaceholder("\u76EE\u6807, Goals, Plan, \u8BA1\u5212, \u6982\u8FF0, Overview").setValue(settings.ui.notePanel.headings.join(", ")).onChange(async (value) => {
        settings.ui.notePanel.headings = value.split(",").map((h) => h.trim()).filter((h) => h.length > 0);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u9ED8\u8BA4\u5C55\u5F00").setDesc("\u9762\u677F\u521D\u59CB\u72B6\u6001\u662F\u5426\u5C55\u5F00").addToggle(
      (toggle) => toggle.setValue(settings.ui.notePanel.defaultExpanded).onChange(async (value) => {
        settings.ui.notePanel.defaultExpanded = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderPhaseList(containerEl, settings) {
    const listEl = containerEl.createDiv({ cls: "tm-settings-phase-list" });
    for (const phase of settings.phases) {
      const phaseEl = listEl.createDiv({ cls: "tm-settings-phase-item" });
      new import_obsidian6.Setting(phaseEl).setName(phase.label + (phase.autoDetected ? " (auto)" : "")).setDesc(`ID: ${phase.id}` + (phase.noteFilePath ? ` | ${phase.noteFilePath}` : "")).addButton(
        (btn) => btn.setButtonText("\u5220\u9664").setWarning().onClick(async () => {
          if (phase.autoDetected) {
            new import_obsidian6.Notice("\u81EA\u52A8\u68C0\u6D4B\u7684\u9636\u6BB5\u4F1A\u5728\u4E0B\u6B21\u626B\u63CF\u65F6\u91CD\u65B0\u51FA\u73B0\uFF0C\u9664\u975E\u79FB\u9664\u7B14\u8BB0\u4E2D\u7684 phase frontmatter\u3002");
          }
          settings.phases = settings.phases.filter((p) => p.id !== phase.id);
          await this.plugin.saveSettings();
          this.display();
        })
      );
      new import_obsidian6.Setting(phaseEl).setName("\u63CF\u8FF0").addTextArea(
        (text) => {
          var _a;
          return text.setPlaceholder("\u9636\u6BB5\u63CF\u8FF0\uFF08\u53EF\u9009\uFF09").setValue((_a = phase.description) != null ? _a : "").onChange(async (value) => {
            phase.description = value || void 0;
            await this.plugin.saveSettings();
          });
        }
      );
    }
    const addEl = containerEl.createDiv({ cls: "tm-settings-add-phase" });
    let newId = "";
    let newLabel = "";
    let newDesc = "";
    new import_obsidian6.Setting(addEl).setName("\u6DFB\u52A0\u65B0\u9636\u6BB5").addText(
      (text) => text.setPlaceholder("\u9636\u6BB5ID (\u5982 mvp)").onChange((value) => {
        newId = value;
      })
    ).addText(
      (text) => text.setPlaceholder("\u663E\u793A\u540D\u79F0 (\u5982 MVP\u9636\u6BB5)").onChange((value) => {
        newLabel = value;
      })
    ).addButton(
      (btn) => btn.setButtonText("\u6DFB\u52A0").setCta().onClick(async () => {
        if (!newId || !newLabel)
          return;
        const validation = this.viewRegistry.isValidPhaseId(newId);
        if (!validation.valid) {
          new import_obsidian6.Notice(`\u65E0\u6548\u7684\u9636\u6BB5ID: ${validation.reason}`);
          return;
        }
        settings.phases.push({
          id: newId,
          label: newLabel,
          order: settings.phases.length,
          description: newDesc || void 0
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian6.Setting(addEl).setName("\u9636\u6BB5\u63CF\u8FF0").addTextArea(
      (text) => text.setPlaceholder("\u9636\u6BB5\u63CF\u8FF0\uFF08\u53EF\u9009\uFF09").onChange((value) => {
        newDesc = value;
      })
    );
  }
};

// src/main.ts
var TaskMakerPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.eventBus = new EventBus();
    this.reconcileTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.tagManager = new TagManagerService(this.app, () => this.settings);
    this.taskScanner = new TaskScannerService(
      this.app,
      this.tagManager,
      this.eventBus,
      () => this.settings
    );
    this.viewRegistry = new ViewRegistryService(() => this.settings);
    this.registerView(
      VIEW_TYPE_MATRIX,
      (leaf) => new MatrixView(
        leaf,
        this.eventBus,
        this.taskScanner,
        this.tagManager,
        this.viewRegistry,
        () => this.settings,
        (file, id, label, start, end) => this.addPhaseToActiveNote(file, id, label, start, end),
        (file, id, label, start, end) => this.completePhaseAttributes(file, id, label, start, end)
      )
    );
    this.addRibbonIcon("layout-grid", "Task Maker Matrix", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-matrix-view",
      name: "Open Eisenhower Matrix",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "rescan-tasks",
      name: "Rescan all tasks",
      callback: async () => {
        await this.taskScanner.fullScan();
        await this.reconcilePhaseNotes();
      }
    });
    this.addSettingTab(new SettingsTab(
      this.app,
      this,
      this.viewRegistry,
      this.eventBus
    ));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian7.TFile && file.extension === "md") {
          this.taskScanner.incrementalScan(file);
        }
      })
    );
    this.eventBus.on("tasks-changed", () => {
      if (this.reconcileTimer)
        clearTimeout(this.reconcileTimer);
      this.reconcileTimer = setTimeout(() => {
        this.reconcilePhaseNotes();
      }, 500);
    });
    this.app.workspace.onLayoutReady(async () => {
      await this.taskScanner.fullScan();
      await this.reconcilePhaseNotes();
    });
  }
  onunload() {
    if (this.reconcileTimer)
      clearTimeout(this.reconcileTimer);
    this.eventBus.clear();
    this.taskScanner.clearCache();
  }
  async loadSettings() {
    var _a, _b, _c;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (data) {
      this.settings.ui = Object.assign({}, DEFAULT_SETTINGS.ui, data.ui);
      if ((_a = data.ui) == null ? void 0 : _a.quadrantLabels) {
        this.settings.ui.quadrantLabels = Object.assign(
          {},
          DEFAULT_SETTINGS.ui.quadrantLabels,
          data.ui.quadrantLabels
        );
      }
      if ((_b = data.ui) == null ? void 0 : _b.quadrantColors) {
        this.settings.ui.quadrantColors = Object.assign(
          {},
          DEFAULT_SETTINGS.ui.quadrantColors,
          data.ui.quadrantColors
        );
      }
      if ((_c = data.ui) == null ? void 0 : _c.notePanel) {
        this.settings.ui.notePanel = Object.assign(
          {},
          DEFAULT_SETTINGS.ui.notePanel,
          data.ui.notePanel
        );
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.eventBus.emit("settings-changed", { settings: this.settings });
  }
  async reconcilePhaseNotes() {
    const detected = this.taskScanner.getDetectedPhases();
    const settings = this.settings;
    let changed = false;
    const added = [];
    const updated = [];
    const removed = [];
    const detectedById = /* @__PURE__ */ new Map();
    for (const info of detected) {
      if (detectedById.has(info.phaseId)) {
        console.warn(`[TaskMaker] Duplicate phase-id "${info.phaseId}" in files: ${detectedById.get(info.phaseId).filePath} and ${info.filePath}`);
        continue;
      }
      detectedById.set(info.phaseId, info);
    }
    for (const [phaseId, info] of detectedById) {
      const existing = settings.phases.find((p) => p.id === phaseId);
      if (existing) {
        if (existing.noteFilePath !== info.filePath) {
          existing.noteFilePath = info.filePath;
          changed = true;
          updated.push(phaseId);
        }
        if (existing.autoDetected && existing.label !== info.phaseLabel) {
          existing.label = info.phaseLabel;
          changed = true;
          if (!updated.includes(phaseId))
            updated.push(phaseId);
        }
        const newTp = info.timePeriod;
        const oldTp = existing.timePeriod;
        if (newTp && (!oldTp || oldTp.start !== newTp.start || oldTp.end !== newTp.end)) {
          existing.timePeriod = newTp;
          changed = true;
          if (!updated.includes(phaseId))
            updated.push(phaseId);
        } else if (!newTp && oldTp && existing.autoDetected) {
          existing.timePeriod = void 0;
          changed = true;
          if (!updated.includes(phaseId))
            updated.push(phaseId);
        }
      } else {
        const validation = this.viewRegistry.isValidPhaseId(phaseId);
        if (!validation.valid) {
          console.warn(`[TaskMaker] Auto-detected phase-id "${phaseId}" is invalid: ${validation.reason}`);
          continue;
        }
        settings.phases.push({
          id: phaseId,
          label: info.phaseLabel,
          order: settings.phases.length,
          noteFilePath: info.filePath,
          timePeriod: info.timePeriod,
          autoDetected: true
        });
        changed = true;
        added.push(phaseId);
      }
    }
    settings.phases = settings.phases.filter((p) => {
      if (!p.autoDetected)
        return true;
      if (detectedById.has(p.id))
        return true;
      removed.push(p.id);
      changed = true;
      return false;
    });
    if (changed) {
      await this.saveSettings();
      this.eventBus.emit("phases-synced", { added, updated, removed });
    }
  }
  async createPhaseNote(phaseId, phaseLabel, phaseStart = "", phaseEnd = "") {
    const validation = this.viewRegistry.isValidPhaseId(phaseId);
    if (!validation.valid) {
      new import_obsidian7.Notice(`\u65E0\u6548\u7684\u9636\u6BB5 ID: ${validation.reason}`);
      return;
    }
    if (this.settings.phases.some((p) => p.id === phaseId)) {
      new import_obsidian7.Notice(`\u9636\u6BB5 "${phaseId}" \u5DF2\u5B58\u5728`);
      return;
    }
    const filePath = `${phaseId}.md`;
    const content = [
      "---",
      "phase: true",
      `phase-id: ${phaseId}`,
      `phase-label: ${phaseLabel}`,
      `phase-start: ${phaseStart}`,
      `phase-end: ${phaseEnd}`,
      "---",
      "",
      `# ${phaseLabel}`,
      ""
    ].join("\n");
    try {
      if (this.app.vault.getAbstractFileByPath(filePath)) {
        new import_obsidian7.Notice(`\u6587\u4EF6 ${filePath} \u5DF2\u5B58\u5728`);
        return;
      }
      await this.app.vault.create(filePath, content);
      new import_obsidian7.Notice(`\u5DF2\u521B\u5EFA\u9636\u6BB5\u7B14\u8BB0: ${filePath}`);
      await this.waitForMetadataCache(filePath);
      await this.taskScanner.fullScan();
      await this.reconcilePhaseNotes();
    } catch (e) {
      new import_obsidian7.Notice(`\u521B\u5EFA\u5931\u8D25: ${e.message}`);
    }
  }
  async addPhaseToActiveNote(file, phaseId, phaseLabel, phaseStart = "", phaseEnd = "") {
    const validation = this.viewRegistry.isValidPhaseId(phaseId);
    if (!validation.valid) {
      new import_obsidian7.Notice(`\u65E0\u6548\u7684\u9636\u6BB5 ID: ${validation.reason}`);
      return;
    }
    if (this.settings.phases.some((p) => p.id === phaseId)) {
      new import_obsidian7.Notice(`\u9636\u6BB5 "${phaseId}" \u5DF2\u5B58\u5728`);
      return;
    }
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.phase = true;
        fm["phase-id"] = phaseId;
        fm["phase-label"] = phaseLabel;
        fm["phase-start"] = phaseStart;
        fm["phase-end"] = phaseEnd;
      });
      new import_obsidian7.Notice(`\u5DF2\u5C06\u9636\u6BB5\u5C5E\u6027\u6DFB\u52A0\u5230: ${file.basename}`);
      await this.waitForMetadataCache(file.path);
      await this.taskScanner.fullScan();
      await this.reconcilePhaseNotes();
    } catch (e) {
      new import_obsidian7.Notice(`\u6DFB\u52A0\u9636\u6BB5\u5C5E\u6027\u5931\u8D25: ${e.message}`);
    }
  }
  async completePhaseAttributes(file, phaseId, phaseLabel, phaseStart = "", phaseEnd = "") {
    if (!phaseId.trim()) {
      new import_obsidian7.Notice("\u9636\u6BB5 ID \u4E0D\u80FD\u4E3A\u7A7A");
      return;
    }
    try {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.phase = true;
        fm["phase-id"] = phaseId;
        fm["phase-label"] = phaseLabel;
        if (phaseStart || !fm["phase-start"])
          fm["phase-start"] = phaseStart;
        if (phaseEnd || !fm["phase-end"])
          fm["phase-end"] = phaseEnd;
      });
      new import_obsidian7.Notice(`\u5DF2\u8865\u5168\u9636\u6BB5\u5C5E\u6027: ${file.basename}`);
      await this.waitForMetadataCache(file.path);
      await this.taskScanner.fullScan();
      await this.reconcilePhaseNotes();
    } catch (e) {
      new import_obsidian7.Notice(`\u8865\u5168\u9636\u6BB5\u5C5E\u6027\u5931\u8D25: ${e.message}`);
    }
  }
  waitForMetadataCache(filePath) {
    return new Promise((resolve) => {
      var _a;
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian7.TFile && ((_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter)) {
        resolve();
        return;
      }
      const timeout = setTimeout(() => {
        this.app.metadataCache.off("resolved", onResolved);
        resolve();
      }, 2e3);
      const onResolved = () => {
        var _a2;
        const f = this.app.vault.getAbstractFileByPath(filePath);
        if (f instanceof import_obsidian7.TFile && ((_a2 = this.app.metadataCache.getFileCache(f)) == null ? void 0 : _a2.frontmatter)) {
          clearTimeout(timeout);
          this.app.metadataCache.off("resolved", onResolved);
          resolve();
        }
      };
      this.app.metadataCache.on("resolved", onResolved);
    });
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_MATRIX);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_MATRIX,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
